Test can handle multiple files + GPG

diff --git a/.github/workflows/push_test.yml b/.github/workflows/push_test.yml
--- a/.github/workflows/push_test.yml
+++ b/.github/workflows/push_test.yml
@@ -99,7 +99,7 @@ jobs:
           rpm_file_path: ${{ steps.build-and-sign-rpm.outputs.rpm_file_path }}
 
 
-  test_action_with_multiple_asset:
+  test_action_with_multiple_assets:
     name: Test build & sign multiple asset RPMs
     runs-on: ubuntu-18.04
     steps:
@@ -115,27 +115,45 @@ jobs:
           gpg_signing_key_id: ${{ secrets.SIMP_DEV_GPG_SIGNING_KEY_ID }}
           gpg_signing_key_passphrase: ${{ secrets.SIMP_DEV_GPG_SIGNING_KEY_PASSPHRASE }}
           path_to_build: tests/asset-with-multiple-packages
-      - name: 'Check basic results'
-        run: |
-          [ -z "$rpm_file_path" ] && { echo '::error ::$rpm_file_path cannot be empty!'; exit 88; }
-          [ -z "$rpm_file_basename" ] && { echo '::error ::$rpm_file_basename cannot be empty!'; exit 88; }
-          if [ ! -f "$rpm_file_path" ]; then
-            printf '::error ::No file found at $rpm_file_path (got "%s")!\n' "$rpm_file_path"
-            exit 88
-          fi
+      - name: 'Check basic RPM results'
         env:
           rpm_file_paths: ${{ steps.build-and-sign-rpm.outputs.rpm_file_paths }}
+        run: |
+          [ -z "$rpm_file_paths" ] && { echo '::error ::$rpm_file_paths cannot be empty!'; exit 88; }
+          files=(${rpm_file_paths//,/ })
+          echo "== rpm_file_paths: $rpm_file_paths"
+          for file in "${files[@]}"; do
+          if [ ! -f "$file" ]; then
+            printf '::error ::No file found at $file (got "%s")!\n' "$file"
+            exit 88
+          fi
+      - name: 'Check basic GPG results'
+        env:
+          gpg_file_path: ${{ steps.build-and-sign-rpm.outputs.gpg_file_path }}
+        run: |
+          [ -z "$gpg_file_path" ] && { echo '::error ::$gpg_file_path cannot be empty!'; exit 88; }
+          if [ ! -f "$gpg_file_path" ]; then
+            printf '::error ::No file found at $gpg_file_path (got "%s")!\n' "$gpg_file_path"
+            exit 88
+          fi
       - run: 'command -v rpm || if command -v apt-get; then sudo apt-get update; sudo apt-get install -y rpm; fi ||:'
       - name: 'Very RPM info is readable'
         run: |
+          files=(${rpm_file_paths//,/ })
           echo "== rpm_file_paths: $rpm_file_paths"
-          rpm -qip "$rpm_file_path" || { echo '::error ::Error reading RPM info from $rpm_file_path'; exit 88; }
+          for file in "${files[@]}"; do
+            echo "-- $file"
+            rpm -qip "$file" || { echo '::error ::Error reading RPM info from $file'; exit 88; }
+          done
         env:
           rpm_file_paths: ${{ steps.build-and-sign-rpm.outputs.rpm_file_paths }}
       - name: 'Very RPM info is correct'
         run: |
-          rpm_version="$(rpm -q --qf '%{RPMTAG_VERSION}' -p "$rpm_file_path")"
-          [[ "$rpm_version" == "1.2.3" ]] || { echo "::error ::Expected RPM version '1.2.3', got '$rpm_version'"; exit 88; }
+          files=(${rpm_file_paths//,/ })
+          for file in "${files[@]}"; do
+            rpm_version="$(rpm -q --qf '%{RPMTAG_VERSION}' -p "$file")"
+            [[ "$rpm_version" == "1.2.3" ]] || { echo "::error ::Expected RPM version '1.2.3', got '$rpm_version': $file"; exit 88; }
+          done
         env:
           rpm_file_paths: ${{ steps.build-and-sign-rpm.outputs.rpm_file_paths }}
 
